In [23]:
import numpy as np
import scipy
import scipy.linalg

In [2]:
#Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:
A = np.array([[3, -1, 1], [2, -5, -3], [1, 1, -1]])
A

array([[ 3, -1,  1],
       [ 2, -5, -3],
       [ 1,  1, -1]])

In [4]:
np.linalg.matrix_rank(A)

3

In [5]:
A_1 = np.array([[3, -1, 1, 4], [2, -5, -3, -17], [1, 1, -1, 0]])
A_1

array([[  3,  -1,   1,   4],
       [  2,  -5,  -3, -17],
       [  1,   1,  -1,   0]])

In [6]:
np.linalg.matrix_rank(A_1)

3

In [7]:
#ранги матриц равны, значит система совместна, ранги матриц равны числу переменных, значит система имеет одно решение

In [8]:
B = np.array([[2, -4, 6], [1, -2, 3], [3, -6, 9]])
B

array([[ 2, -4,  6],
       [ 1, -2,  3],
       [ 3, -6,  9]])

In [9]:
np.linalg.matrix_rank(B)

1

In [10]:
B_1 = np.array([[2, -4, 6, 1], [1, -2, 3, -2], [3, -6, 9, 5]])
B_1

array([[ 2, -4,  6,  1],
       [ 1, -2,  3, -2],
       [ 3, -6,  9,  5]])

In [11]:
np.linalg.matrix_rank(B_1)

2

In [12]:
#ранги матриц не равны, значит система несовместна, решений не имеет

In [17]:
C = np.array([[1, 2, 5], [3, 1, -8]])
C

array([[ 1,  2,  5],
       [ 3,  1, -8]])

In [18]:
np.linalg.matrix_rank(C)

2

In [19]:
C_1 = np.array([[1, 2, 5, 4], [3, 1, -8, -2]])
C_1

array([[ 1,  2,  5,  4],
       [ 3,  1, -8, -2]])

In [20]:
np.linalg.matrix_rank(C_1)

2

In [21]:
#ранги матриц равны, значит система совместна, ранги матриц меньше числа переменных, 
#значит система имеет бесконечное множество решений

In [26]:
#Найти 𝐿-матрицу 𝐿𝑈-разложения для матрицы коэффициентов:
M = np.array([[1, 2, 4], [2, 9, 12], [3, 26, 30]])
P, L, U = scipy.linalg.lu(M)
print(L)

[[1.         0.         0.        ]
 [0.66666667 1.         0.        ]
 [0.33333333 0.8        1.        ]]


In [28]:
M_1 = np.array([[1, 1, 2, 4], [2, 5, 8, 9], [3, 18, 29, 18], [4, 22, 53, 33]])
P, L, U = scipy.linalg.lu(M_1)
print(L)

[[ 1.          0.          0.          0.        ]
 [ 0.5         1.          0.          0.        ]
 [ 0.75       -0.25        1.          0.        ]
 [ 0.25        0.75       -0.17073171  1.        ]]
