In [30]:
import numpy as np

In [31]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
det_A = np.linalg.det(A)
det_A

6.66133814775094e-16

In [33]:
a = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
a

array([[ -2,   7,  -3],
       [  4, -14,   6],
       [ -3,   7,  13]])

In [34]:
det_a = np.linalg.det(a)
det_a

0.0

In [36]:
B = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
B

array([[1, 2, 3],
       [1, 1, 1],
       [2, 3, 4]])

In [37]:
r_B = np.linalg.matrix_rank(B)
r_B

2