In [1]:
import numpy as np

In [2]:
#найти сумму и произведение матриц
A = np.array([[1, -2], [3, 0]])
A

array([[ 1, -2],
       [ 3,  0]])

In [3]:
B = np.array([[4, 1], [0, 5]])
B

array([[4, 1],
       [0, 5]])

In [5]:
C1 = A.dot(B)
C1

array([[ 4, -9],
       [12,  3]])

In [7]:
C2 = B.dot(A)
C2

array([[ 7, -8],
       [15,  0]])

In [8]:
#вычислить 3А - 2В + 4С
A1 = np.array([[1, 7], [3, -6]])
A1

array([[ 1,  7],
       [ 3, -6]])

In [9]:
B1 = np.array([[0, 5], [2, -1]])
B1

array([[ 0,  5],
       [ 2, -1]])

In [11]:
C1 = np.array([[2, -4], [1, 1]])
C1

array([[ 2, -4],
       [ 1,  1]])

In [12]:
D = 3 * A1 - 2 * B1 + 4 * C1 
D

array([[ 11,  -5],
       [  9, -12]])

In [13]:
#Вычислить А*At и At*A
A2 = np.array([[4, 1], [5, -2], [2, 3]])
A2

array([[ 4,  1],
       [ 5, -2],
       [ 2,  3]])

In [17]:
At = A2.transpose()
At

array([[ 4,  5,  2],
       [ 1, -2,  3]])

In [19]:
AAt = A2.dot(At)
AAt

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [20]:
AtA = At.dot(A2)
AtA

array([[45,  0],
       [ 0, 14]])